### ISSUE TITLE
Good url are detected like spam.

### ISSUE THREAD

**Issue by NicolasDaigneault** [YOURLS/antispam#17]
I have some url that are erased overtime because they are detected like spam.  Sometime i'm not able to create it, other time they are erased later.

The url that are erased have domain like:

https://goo.gl/forms/
https://docs.google.com
https://fr.padlet.com/

I used the lookup for this website:
'dbl.spamhaus.org',
'multi.surbl.org',
'black.uribl.com',
and found that my url erased are not blacklisted.  So i'm not sure of what to check right now. 

I'm alone with this problem?

**Comment by webmarka** [comment]
You could take a look at the output into the plugin.php file, see `ozh_yourls_antispam_is_blacklisted()` function and add at line 98 : 

`var_dump($record);`

I found that one of my installs was hitting an error message from black.uribl.com : 

```
array(2) {
  [0]=>
  array(5) {
    ["host"]=>
    string(29) "mydomain.com.black.uribl.com"
    ["class"]=>
    string(2) "IN"
    ["ttl"]=>
    int(1594)
    ["type"]=>
    string(1) "A"
    ["ip"]=>
    string(9) "127.0.0.1"
  }
  [1]=>
  array(6) {
    ["host"]=>
    string(29) "mydomain.com.black.uribl.com"
    ["class"]=>
    string(2) "IN"
    ["ttl"]=>
    int(1594)
    ["type"]=>
    string(3) "TXT"
    ["txt"]=>
    string(110) "127.0.0.1 -> Query Refused. See http://uribl.com/refused.shtml for more information [Your DNS IP: XX.XXX.XX.X]"
    ["entries"]=>
    array(1) {
      [0]=>
      string(110) "127.0.0.1 -> Query Refused. See http://uribl.com/refused.shtml for more information [Your DNS IP: XX.XXX.XX.X]"
    }
  }
}
```

So when this occurs, it will flag the domain as spam as no check is done on the RBL answer in the plugin.

My solution was to temporarily disable this RBL in my functions.php file : 

```
// Antispam RBLs List
yourls_add_filter( 'ozh_yourls_antispam_list', 'my_ozh_yourls_antispam_list' );
function refr_ozh_yourls_antispam_list($array) {
	
	unset($array[2]); #black.uribl.com
	
	return $array;
}
```

This solves the problem at least temporarily until the particular RBL error is fixed!

**Comment by webmarka** [comment]
I confirm that black.uribl.com does not seems to work and commenting it temporarily solves the problem.

**Comment by armandg** [comment]
Can confirm that @webmarka's solutions works, but what I did was commenting line 90:

```
	$blacklists = yourls_apply_filter( 'ozh_yourls_antispam_list',
		array(
			'dbl.spamhaus.org',
			'multi.surbl.org',
//			'black.uribl.com',
		)
	);
```

**Comment by ozh** [comment]
Maybe replacing black.uribl.com with multi.uribl.com would work, it seems they have renamed a couple stuff since the creation of this plugin

**Comment by armandg** [comment]
@ozh Nope, that gives an error.
