### ISSUE TITLE
Dropbox is not spam

### ISSUE THREAD

**Issue by drbeco** [YOURLS/antispam#22]
### Description

Dropbox link is detected as spam, but this is a fairly known enterprise and it is not spam. Thanks

**Comment by dgw** [comment]
The actual spam domains come from external lists:

https://github.com/YOURLS/antispam/blob/2231da26d8acf730ffe928f2a11e25135808b353/plugin.php#L85-L93

You'll need to request whichever blocklist has listed the domain to remove it.

NB: Plenty of phishing and malware campaigns via email and other methods use Box, Dropbox, Mega, etc. links to appear trustworthy. This is probably why one (or more) of the blocklists this plugin uses have banned Dropbox.

**Comment by drbeco** [comment]
Can we tune in blacklists within this plugin?

**Comment by ozh** [comment]
@drbeco yes, there is a filter exactly for this on line 86
Or, duplicate the plugin and edit it to suit your needs
